### ISSUE TITLE
Initial cron expression is not loaded in the form

### ISSUE THREAD

**Issue by Franccescalee** [haavardj/ngx-cron-editor#15]
I have an add/edit form for scheduling reports. When editing, the cron editor does not set the initial cron expression in the form. I was expecting it to show the tab for the current cron expression as selected and also reflect the selected values. The editor loads OK but when I select that tab to see if the selected values are shown in the form it resets the expression.

I tried using the [cron] Input and passing the initial value with that as well as the FormControl but I still get the same behavior.

I am using version 0.7.4 in an Angular 14.2.10 app.

**Comment by Zegorax** [comment]
I have the same problem.

As from I inspected into the code, when handleModelChange() is called, this method will not update the field values.

It seems also that there is no subscription to the cron expression changing in the component. Therefore, when updating the expression from an external source, it will not update the internal cron state or compute again the cron values.

**Comment by sstinson91** [comment]
I'm having the same problem.

**Comment by cpdk** [comment]
I see this on 0.7.8 on Angular 16

**Comment by raBot1994** [comment]
Hi did anyone find a solution to this?

**Comment by haavardj** [comment]
You’re right. The cron editor ignores any initial value or changes to the input in the form control. Each tab has its own initial and internal state that will be output to the formControl when that tab is selected. This is somewhat a legacy of the fork source, but it is also non-trivial to parse and update the internal state from input (e.g., what tab to open). Input might be incomplete, erroneous (e.g., illegal characters, too many fields), or fit multiple tabs. 

I have some ideas that I will try out, but that requires some rewiring of the component's internal state. Stay tuned. Ideas and patches are always welcome :-)

**Comment by haavardj** [comment]
Please try out ngx-cron-editor@0.7.9-0 and see if that works for you.

**Comment by raBot1994** [comment]
@haavardj would a patchValue with a cron expression work in 0.7.9-0 or is anything additional required?

**Comment by haavardj** [comment]
@raBot1994 Yes, that should now work for most cron expressions. There are exotic/advanced expressions that the editor currently cannot parse. That will be left for future updates. Please give it a spin and see if it looks ok.

**Comment by bhardwajvinay004** [comment]
@haavardj Could you please make it compatible with previous Angular versions (Angular 12)?

**Comment by haavardj** [comment]
Version 0.7.9 is published on NPM.

**Comment by sstinson91** [comment]
Thanks for the update! I tried this update with Angular 14 but got the following error:

Error: node_modules/ngx-cron-editor/src/cron-time-picker.component.d.ts:25:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

25     static ɵcmp: i0.ɵɵComponentDeclaration<TimePickerComponent, "cron-time-picker", never, { "disabled": { "alias": "disabled"; "required": false; }; "use24HourTime": { "alias": "use24HourTime"; "required": false; }; "hideHours": { "alias": "hideHours"; "required": false; }; "hideMinutes": { "alias": "hideMinutes"; "required": false; }; "hideSeconds": { "alias": "hideSeconds"; "required": false; }; }, {}, never, never, false, never>;


Any ideas?

**Comment by sstinson91** [comment]
I've upgraded to Angular 15 and I'm using v0.7.9. I'm still getting the error above, but I've found a band aid fix. However, the initial cron value still isn't loading. @haavardj
