### ISSUE TITLE
Import of CronEditorModule is not working in version 0.8.3

### ISSUE THREAD

**Issue by miroslavmachalek** [haavardj/ngx-cron-editor#43]
We updated ngx-cron-editor to 0.8.3 and `import { CronEditorModule } from 'ngx-cron-editor';` is not working anymore.

We are becoming this error:
`error TS2307: Cannot find module 'ngx-cron-editor' or its corresponding type declarations.`

Our Angular version is `18.2.6` and we can still use our project with version 0.8.2, even if peerDependencies are not right.

Thank you!

**Comment by Cody-Fah** [comment]
We are experiencing this as well

**Comment by haavardj** [comment]
Let me check... Perhaps something went wrong in the build.

**Comment by haavardj** [comment]
Pushed version 0.8.4 to npm. Let me know if the issue remains after updating.

**Comment by miroslavmachalek** [comment]
Thank you, it looks good now.
